const micronutrientData = [
    // Vitamin A (μg/day)
    { nutrient: "Vitamin A", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 0.58, age_end: 3, value: 250, gender: "Both" },
    { nutrient: "Vitamin A", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 4, age_end: 6, value: 250, gender: "Both" },
    { nutrient: "Vitamin A", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 7, age_end: 10, value: 400, gender: "Both" },
    { nutrient: "Vitamin A", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 11, age_end: 14, value: 600, gender: "Both" },
    { nutrient: "Vitamin A", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 15, age_end: 17, value: 750, gender: "Male" },
    { nutrient: "Vitamin A", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 15, age_end: 17, value: 650, gender: "Female" },
    { nutrient: "Vitamin A", source: "EFSA", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 800, gender: "Both" },
    { nutrient: "Vitamin A", source: "EFSA", type: "UL", unit: "μg/day", age_start: 4, age_end: 6, value: 800, gender: "Both" },
    { nutrient: "Vitamin A", source: "EFSA", type: "UL", unit: "μg/day", age_start: 7, age_end: 10, value: 1100, gender: "Both" },
    { nutrient: "Vitamin A", source: "EFSA", type: "UL", unit: "μg/day", age_start: 11, age_end: 14, value: 1700, gender: "Both" },
    { nutrient: "Vitamin A", source: "EFSA", type: "UL", unit: "μg/day", age_start: 15, age_end: 17, value: 2300, gender: "Both" },
    { nutrient: "Vitamin A", source: "FNB", type: "RDA", unit: "μg/day", age_start: 1, age_end: 3, value: 300, gender: "Both" },
    { nutrient: "Vitamin A", source: "FNB", type: "RDA", unit: "μg/day", age_start: 4, age_end: 8, value: 400, gender: "Both" },
    { nutrient: "Vitamin A", source: "FNB", type: "RDA", unit: "μg/day", age_start: 9, age_end: 13, value: 600, gender: "Both" },
    { nutrient: "Vitamin A", source: "FNB", type: "RDA", unit: "μg/day", age_start: 14, age_end: 18, value: 900, gender: "Male" },
    { nutrient: "Vitamin A", source: "FNB", type: "RDA", unit: "μg/day", age_start: 14, age_end: 18, value: 700, gender: "Female" },
    { nutrient: "Vitamin A", source: "FNB", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 600, gender: "Both" },
    { nutrient: "Vitamin A", source: "FNB", type: "UL", unit: "μg/day", age_start: 4, age_end: 8, value: 900, gender: "Both" },
    { nutrient: "Vitamin A", source: "FNB", type: "UL", unit: "μg/day", age_start: 9, age_end: 13, value: 1700, gender: "Both" },
    { nutrient: "Vitamin A", source: "FNB", type: "UL", unit: "μg/day", age_start: 14, age_end: 18, value: 2800, gender: "Both" },
    { nutrient: "Vitamin A", source: "TFC", type: "DRV", unit: "μg/day", age_start: 4, age_end: 18, value: 800, gender: "Both" },
    { nutrient: "Vitamin A", source: "TFC", type: "DML", unit: "μg/day", age_start: 4, age_end: 10, value: 1200, gender: "Both" },
    { nutrient: "Vitamin A", source: "TFC", type: "DML", unit: "μg/day", age_start: 11, age_end: 18, value: 3000, gender: "Both" },
    // Biotin (μg/day)
    { nutrient: "Biotin", source: "EFSA", type: "AI", unit: "μg/day", age_start: 0.58, age_end: 3, value: 20, gender: "Both" },
    { nutrient: "Biotin", source: "EFSA", type: "AI", unit: "μg/day", age_start: 4, age_end: 10, value: 25, gender: "Both" },
    { nutrient: "Biotin", source: "EFSA", type: "AI", unit: "μg/day", age_start: 11, age_end: 17, value: 35, gender: "Both" },
    { nutrient: "Biotin", source: "FNB", type: "AI", unit: "μg/day", age_start: 1, age_end: 3, value: 8, gender: "Both" },
    { nutrient: "Biotin", source: "FNB", type: "AI", unit: "μg/day", age_start: 4, age_end: 8, value: 12, gender: "Both" },
    { nutrient: "Biotin", source: "FNB", type: "AI", unit: "μg/day", age_start: 9, age_end: 13, value: 20, gender: "Both" },
    { nutrient: "Biotin", source: "FNB", type: "AI", unit: "μg/day", age_start: 14, age_end: 18, value: 25, gender: "Both" },
    { nutrient: "Biotin", source: "TFC", type: "DRV", unit: "μg/day", age_start: 4, age_end: 18, value: 50, gender: "Both" },
    { nutrient: "Biotin", source: "TFC", type: "DML", unit: "μg/day", age_start: 4, age_end: 10, value: 1250, gender: "Both" },
    { nutrient: "Biotin", source: "TFC", type: "DML", unit: "μg/day", age_start: 11, age_end: 18, value: 5000, gender: "Both" },
    // Calcium (mg/day)
    { nutrient: "Calcium", source: "EFSA", type: "AI", unit: "mg/day", age_start: 0.58, age_end: 0.92, value: 280, gender: "Both" },
    { nutrient: "Calcium", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 1, age_end: 3, value: 450, gender: "Both" },
    { nutrient: "Calcium", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 4, age_end: 10, value: 800, gender: "Both" },
    { nutrient: "Calcium", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 17, value: 1150, gender: "Both" },
    { nutrient: "Calcium", source: "FNB", type: "AI", unit: "mg/day", age_start: 1, age_end: 3, value: 500, gender: "Both" },
    { nutrient: "Calcium", source: "FNB", type: "AI", unit: "mg/day", age_start: 4, age_end: 8, value: 800, gender: "Both" },
    { nutrient: "Calcium", source: "FNB", type: "AI", unit: "mg/day", age_start: 9, age_end: 18, value: 1300, gender: "Both" },
    { nutrient: "Calcium", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 8, value: 2500, gender: "Both" },
    { nutrient: "Calcium", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 18, value: 2500, gender: "Both" },
    { nutrient: "Calcium", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 800, gender: "Both" },
    { nutrient: "Calcium", source: "TFC", type: "DML", unit: "mg/day", age_start: 4, age_end: 10, value: 750, gender: "Both" },
    { nutrient: "Calcium", source: "TFC", type: "DML", unit: "mg/day", age_start: 11, age_end: 18, value: 1500, gender: "Both" },
    // Chloride (mg/day) - CONVERTED FROM g/day
    { nutrient: "Chloride", source: "EFSA", type: "Safe and adequate intake", unit: "mg/day", age_start: 1, age_end: 3, value: 1700, gender: "Both" },
    { nutrient: "Chloride", source: "EFSA", type: "Safe and adequate intake", unit: "mg/day", age_start: 4, age_end: 6, value: 2000, gender: "Both" },
    { nutrient: "Chloride", source: "EFSA", type: "Safe and adequate intake", unit: "mg/day", age_start: 7, age_end: 10, value: 2500, gender: "Both" },
    { nutrient: "Chloride", source: "EFSA", type: "Safe and adequate intake", unit: "mg/day", age_start: 11, age_end: 17, value: 3100, gender: "Both" },
    { nutrient: "Chloride", source: "FNB", type: "AI", unit: "mg/day", age_start: 1, age_end: 3, value: 1500, gender: "Both" },
    { nutrient: "Chloride", source: "FNB", type: "AI", unit: "mg/day", age_start: 4, age_end: 8, value: 1900, gender: "Both" },
    { nutrient: "Chloride", source: "FNB", type: "AI", unit: "mg/day", age_start: 9, age_end: 18, value: 2300, gender: "Both" },
    { nutrient: "Chloride", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 800, gender: "Both" },
    // Choline (mg/day) - CONVERTED FROM g/day
    { nutrient: "Choline", source: "FNB", type: "AI", unit: "mg/day", age_start: 1, age_end: 3, value: 200, gender: "Both" },
    { nutrient: "Choline", source: "FNB", type: "AI", unit: "mg/day", age_start: 4, age_end: 8, value: 250, gender: "Both" },
    { nutrient: "Choline", source: "FNB", type: "AI", unit: "mg/day", age_start: 9, age_end: 13, value: 375, gender: "Both" },
    { nutrient: "Choline", source: "FNB", type: "AI", unit: "mg/day", age_start: 14, age_end: 18, value: 550, gender: "Male" },
    { nutrient: "Choline", source: "FNB", type: "AI", unit: "mg/day", age_start: 14, age_end: 18, value: 400, gender: "Female" },
    { nutrient: "Choline", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 8, value: 1000, gender: "Both" },
    { nutrient: "Choline", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 13, value: 2000, gender: "Both" },
    { nutrient: "Choline", source: "FNB", type: "UL", unit: "mg/day", age_start: 14, age_end: 18, value: 3000, gender: "Both" },
    // Copper (μg/day) - CONVERTED FROM mg/day
    { nutrient: "Copper", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 1, age_end: 3, value: 700, gender: "Both" },
    { nutrient: "Copper", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 4, age_end: 6, value: 800, gender: "Both" },
    { nutrient: "Copper", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 7, age_end: 10, value: 1000, gender: "Both" },
    { nutrient: "Copper", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 11, age_end: 14, value: 1300, gender: "Male" },
    { nutrient: "Copper", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 11, age_end: 14, value: 1100, gender: "Female" },
    { nutrient: "Copper", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 15, age_end: 17, value: 1500, gender: "Male" },
    { nutrient: "Copper", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 15, age_end: 17, value: 1100, gender: "Female" },
    { nutrient: "Copper", source: "EFSA", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 1000, gender: "Both" },
    { nutrient: "Copper", source: "EFSA", type: "UL", unit: "μg/day", age_start: 4, age_end: 6, value: 2000, gender: "Both" },
    { nutrient: "Copper", source: "EFSA", type: "UL", unit: "μg/day", age_start: 7, age_end: 10, value: 3000, gender: "Both" },
    { nutrient: "Copper", source: "EFSA", type: "UL", unit: "μg/day", age_start: 11, age_end: 14, value: 4000, gender: "Both" },
    { nutrient: "Copper", source: "EFSA", type: "UL", unit: "μg/day", age_start: 15, age_end: 17, value: 5000, gender: "Both" },
    { nutrient: "Copper", source: "FNB", type: "RDA", unit: "μg/day", age_start: 1, age_end: 3, value: 340, gender: "Both" },
    { nutrient: "Copper", source: "FNB", type: "RDA", unit: "μg/day", age_start: 4, age_end: 8, value: 440, gender: "Both" },
    { nutrient: "Copper", source: "FNB", type: "RDA", unit: "μg/day", age_start: 9, age_end: 13, value: 700, gender: "Both" },
    { nutrient: "Copper", source: "FNB", type: "RDA", unit: "μg/day", age_start: 14, age_end: 18, value: 890, gender: "Both" },
    { nutrient: "Copper", source: "FNB", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 1000, gender: "Both" },
    { nutrient: "Copper", source: "FNB", type: "UL", unit: "μg/day", age_start: 4, age_end: 8, value: 3000, gender: "Both" },
    { nutrient: "Copper", source: "FNB", type: "UL", unit: "μg/day", age_start: 9, age_end: 13, value: 5000, gender: "Both" },
    { nutrient: "Copper", source: "FNB", type: "UL", unit: "μg/day", age_start: 14, age_end: 18, value: 8000, gender: "Both" },
    { nutrient: "Copper", source: "TFC", type: "DRV", unit: "μg/day", age_start: 4, age_end: 18, value: 1000, gender: "Both" },
    { nutrient: "Copper", source: "TFC", type: "DML", unit: "μg/day", age_start: 4, age_end: 10, value: 1000, gender: "Both" },
    { nutrient: "Copper", source: "TFC", type: "DML", unit: "μg/day", age_start: 11, age_end: 18, value: 2000, gender: "Both" },
    // Fluoride (mg/day)
    { nutrient: "Fluoride", source: "EFSA", type: "AI", unit: "mg/day", age_start: 1, age_end: 3, value: 0.8, gender: "Both" },
    { nutrient: "Fluoride", source: "EFSA", type: "AI", unit: "mg/day", age_start: 4, age_end: 6, value: 1.2, gender: "Both" },
    { nutrient: "Fluoride", source: "EFSA", type: "AI", unit: "mg/day", age_start: 7, age_end: 9, value: 1.7, gender: "Both" },
    { nutrient: "Fluoride", source: "EFSA", type: "AI", unit: "mg/day", age_start: 10, age_end: 14, value: 2.8, gender: "Male" },
    { nutrient: "Fluoride", source: "EFSA", type: "AI", unit: "mg/day", age_start: 10, age_end: 14, value: 2.3, gender: "Female" },
    { nutrient: "Fluoride", source: "EFSA", type: "AI", unit: "mg/day", age_start: 15, age_end: 17, value: 3.2, gender: "Male" },
    { nutrient: "Fluoride", source: "EFSA", type: "AI", unit: "mg/day", age_start: 15, age_end: 17, value: 2.9, gender: "Female" },
    { nutrient: "Fluoride", source: "EFSA", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 1.5, gender: "Both" },
    { nutrient: "Fluoride", source: "EFSA", type: "UL", unit: "mg/day", age_start: 4, age_end: 6, value: 2.5, gender: "Both" },
    { nutrient: "Fluoride", source: "EFSA", type: "UL", unit: "mg/day", age_start: 7, age_end: 8, value: 3.5, gender: "Both" },
    { nutrient: "Fluoride", source: "EFSA", type: "UL", unit: "mg/day", age_start: 9, age_end: 14, value: 5, gender: "Both" },
    { nutrient: "Fluoride", source: "EFSA", type: "UL", unit: "mg/day", age_start: 15, age_end: 17, value: 7, gender: "Both" },
    { nutrient: "Fluoride", source: "FNB", type: "AI", unit: "mg/day", age_start: 1, age_end: 3, value: 0.7, gender: "Both" },
    { nutrient: "Fluoride", source: "FNB", type: "AI", unit: "mg/day", age_start: 4, age_end: 8, value: 1, gender: "Both" },
    { nutrient: "Fluoride", source: "FNB", type: "AI", unit: "mg/day", age_start: 9, age_end: 13, value: 2, gender: "Both" },
    { nutrient: "Fluoride", source: "FNB", type: "AI", unit: "mg/day", age_start: 14, age_end: 18, value: 3, gender: "Both" },
    { nutrient: "Fluoride", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 1.3, gender: "Both" },
    { nutrient: "Fluoride", source: "FNB", type: "UL", unit: "mg/day", age_start: 4, age_end: 8, value: 2.2, gender: "Both" },
    { nutrient: "Fluoride", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 18, value: 10, gender: "Both" },
    { nutrient: "Fluoride", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 3.5, gender: "Both" },
    { nutrient: "Fluoride", source: "TFC", type: "DML", unit: "mg/day", age_start: 4, age_end: 10, value: 1.75, gender: "Both" },
    { nutrient: "Fluoride", source: "TFC", type: "DML", unit: "mg/day", age_start: 11, age_end: 18, value: 3.5, gender: "Both" },
    // Folate (μg/day)
    { nutrient: "Folate", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 1, age_end: 3, value: 100, gender: "Both" },
    { nutrient: "Folate", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 4, age_end: 6, value: 150, gender: "Both" },
    { nutrient: "Folate", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 7, age_end: 10, value: 230, gender: "Both" },
    { nutrient: "Folate", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 11, age_end: 14, value: 330, gender: "Both" },
    { nutrient: "Folate", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 15, age_end: 17, value: 330, gender: "Both" },
    { nutrient: "Folate", source: "EFSA", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 200, gender: "Both" },
    { nutrient: "Folate", source: "EFSA", type: "UL", unit: "μg/day", age_start: 4, age_end: 6, value: 300, gender: "Both" },
    { nutrient: "Folate", source: "EFSA", type: "UL", unit: "μg/day", age_start: 7, age_end: 10, value: 400, gender: "Both" },
    { nutrient: "Folate", source: "EFSA", type: "UL", unit: "μg/day", age_start: 11, age_end: 14, value: 600, gender: "Both" },
    { nutrient: "Folate", source: "EFSA", type: "UL", unit: "μg/day", age_start: 15, age_end: 17, value: 800, gender: "Both" },
    { nutrient: "Folate", source: "FNB", type: "RDA", unit: "μg/day", age_start: 1, age_end: 3, value: 150, gender: "Both" },
    { nutrient: "Folate", source: "FNB", type: "RDA", unit: "μg/day", age_start: 4, age_end: 8, value: 200, gender: "Both" },
    { nutrient: "Folate", source: "FNB", type: "RDA", unit: "μg/day", age_start: 9, age_end: 13, value: 300, gender: "Both" },
    { nutrient: "Folate", source: "FNB", type: "RDA", unit: "μg/day", age_start: 14, age_end: 18, value: 400, gender: "Both" },
    { nutrient: "Folate", source: "FNB", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 300, gender: "Both" },
    { nutrient: "Folate", source: "FNB", type: "UL", unit: "μg/day", age_start: 4, age_end: 8, value: 400, gender: "Both" },
    { nutrient: "Folate", source: "FNB", type: "UL", unit: "μg/day", age_start: 9, age_end: 13, value: 600, gender: "Both" },
    { nutrient: "Folate", source: "FNB", type: "UL", unit: "μg/day", age_start: 14, age_end: 18, value: 800, gender: "Both" },
    { nutrient: "Folate", source: "TFC", type: "DRV", unit: "μg/day", age_start: 4, age_end: 18, value: 200, gender: "Both" },
    { nutrient: "Folate", source: "TFC", type: "DML", unit: "μg/day", age_start: 4, age_end: 10, value: 300, gender: "Both" },
    { nutrient: "Folate", source: "TFC", type: "DML", unit: "μg/day", age_start: 11, age_end: 18, value: 600, gender: "Both" },
    // Iodine (μg/day)
    { nutrient: "Iodine", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 1, age_end: 3, value: 70, gender: "Both" },
    { nutrient: "Iodine", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 4, age_end: 6, value: 90, gender: "Both" },
    { nutrient: "Iodine", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 7, age_end: 10, value: 120, gender: "Both" },
    { nutrient: "Iodine", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 11, age_end: 14, value: 130, gender: "Both" },
    { nutrient: "Iodine", source: "EFSA", type: "PRI", unit: "μg/day", age_start: 15, age_end: 17, value: 150, gender: "Both" },
    { nutrient: "Iodine", source: "EFSA", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 200, gender: "Both" },
    { nutrient: "Iodine", source: "EFSA", type: "UL", unit: "μg/day", age_start: 4, age_end: 6, value: 200, gender: "Both" },
    { nutrient: "Iodine", source: "EFSA", type: "UL", unit: "μg/day", age_start: 7, age_end: 10, value: 250, gender: "Both" },
    { nutrient: "Iodine", source: "EFSA", type: "UL", unit: "μg/day", age_start: 11, age_end: 14, value: 450, gender: "Both" },
    { nutrient: "Iodine", source: "EFSA", type: "UL", unit: "μg/day", age_start: 15, age_end: 17, value: 500, gender: "Both" },
    { nutrient: "Iodine", source: "FNB", type: "RDA", unit: "μg/day", age_start: 1, age_end: 8, value: 90, gender: "Both" },
    { nutrient: "Iodine", source: "FNB", type: "RDA", unit: "μg/day", age_start: 9, age_end: 13, value: 120, gender: "Both" },
    { nutrient: "Iodine", source: "FNB", type: "RDA", unit: "μg/day", age_start: 14, age_end: 18, value: 150, gender: "Both" },
    { nutrient: "Iodine", source: "FNB", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 200, gender: "Both" },
    { nutrient: "Iodine", source: "FNB", type: "UL", unit: "μg/day", age_start: 4, age_end: 8, value: 300, gender: "Both" },
    { nutrient: "Iodine", source: "FNB", type: "UL", unit: "μg/day", age_start: 9, age_end: 13, value: 600, gender: "Both" },
    { nutrient: "Iodine", source: "FNB", type: "UL", unit: "μg/day", age_start: 14, age_end: 18, value: 900, gender: "Both" },
    { nutrient: "Iodine", source: "TFC", type: "DRV", unit: "μg/day", age_start: 4, age_end: 18, value: 150, gender: "Both" },
    { nutrient: "Iodine", source: "TFC", type: "DML", unit: "μg/day", age_start: 4, age_end: 10, value: 75, gender: "Both" },
    { nutrient: "Iodine", source: "TFC", type: "DML", unit: "μg/day", age_start: 11, age_end: 18, value: 150, gender: "Both" },
    // Iron (mg/day)
    { nutrient: "Iron", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 1, age_end: 3, value: 6, gender: "Both" },
    { nutrient: "Iron", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 4, age_end: 6, value: 7, gender: "Both" },
    { nutrient: "Iron", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 7, age_end: 10, value: 8, gender: "Both" },
    { nutrient: "Iron", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 17, value: 11, gender: "Male" },
    { nutrient: "Iron", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 17, value: 13, gender: "Female" },
    { nutrient: "Iron", source: "EFSA", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 20, gender: "Both" },
    { nutrient: "Iron", source: "EFSA", type: "UL", unit: "mg/day", age_start: 4, age_end: 6, value: 25, gender: "Both" },
    { nutrient: "Iron", source: "EFSA", type: "UL", unit: "mg/day", age_start: 7, age_end: 10, value: 30, gender: "Both" },
    { nutrient: "Iron", source: "EFSA", type: "UL", unit: "mg/day", age_start: 11, age_end: 17, value: 40, gender: "Both" },
    { nutrient: "Iron", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 7, gender: "Both" },
    { nutrient: "Iron", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 10, gender: "Both" },
    { nutrient: "Iron", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 13, value: 8, gender: "Both" },
    { nutrient: "Iron", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 11, gender: "Male" },
    { nutrient: "Iron", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 15, gender: "Female" },
    { nutrient: "Iron", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 13, value: 40, gender: "Both" },
    { nutrient: "Iron", source: "FNB", type: "UL", unit: "mg/day", age_start: 14, age_end: 18, value: 45, gender: "Both" },
    { nutrient: "Iron", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 14, gender: "Both" },
    { nutrient: "Iron", source: "TFC", type: "DML", unit: "mg/day", age_start: 4, age_end: 10, value: 8.5, gender: "Both" },
    { nutrient: "Iron", source: "TFC", type: "DML", unit: "mg/day", age_start: 11, age_end: 18, value: 17, gender: "Both" },
    // Magnesium (mg/day)
    { nutrient: "Magnesium", source: "EFSA", type: "AI", unit: "mg/day", age_start: 1, age_end: 2, value: 80, gender: "Both" },
    { nutrient: "Magnesium", source: "EFSA", type: "AI", unit: "mg/day", age_start: 3, age_end: 3, value: 170, gender: "Both" },
    { nutrient: "Magnesium", source: "EFSA", type: "AI", unit: "mg/day", age_start: 4, age_end: 6, value: 170, gender: "Both" },
    { nutrient: "Magnesium", source: "EFSA", type: "AI", unit: "mg/day", age_start: 7, age_end: 10, value: 230, gender: "Both" },
    { nutrient: "Magnesium", source: "EFSA", type: "AI", unit: "mg/day", age_start: 11, age_end: 17, value: 390, gender: "Male" },
    { nutrient: "Magnesium", source: "EFSA", type: "AI", unit: "mg/day", age_start: 11, age_end: 14, value: 280, gender: "Female" },
    { nutrient: "Magnesium", source: "EFSA", type: "AI", unit: "mg/day", age_start: 15, age_end: 17, value: 300, gender: "Female" },
    { nutrient: "Magnesium", source: "EFSA", type: "UL", unit: "mg/day", age_start: 1, age_end: 17, value: 250, gender: "Both" },
    { nutrient: "Magnesium", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 80, gender: "Both" },
    { nutrient: "Magnesium", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 130, gender: "Both" },
    { nutrient: "Magnesium", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 13, value: 240, gender: "Both" },
    { nutrient: "Magnesium", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 410, gender: "Male" },
    { nutrient: "Magnesium", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 360, gender: "Female" },
    { nutrient: "Magnesium", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 65, gender: "Both" },
    { nutrient: "Magnesium", source: "FNB", type: "UL", unit: "mg/day", age_start: 4, age_end: 8, value: 110, gender: "Both" },
    { nutrient: "Magnesium", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 18, value: 350, gender: "Both" },
    { nutrient: "Magnesium", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 375, gender: "Both" },
    { nutrient: "Magnesium", source: "TFC", type: "DML", unit: "mg/day", age_start: 4, age_end: 18, value: 187.5, gender: "Both" },
    // Manganese (mg/day)
    { nutrient: "Manganese", source: "EFSA", type: "Safe and adequate intake", unit: "mg/day", age_start: 1, age_end: 17, value: 2, gender: "Both" },
    { nutrient: "Manganese", source: "FNB", type: "AI", unit: "mg/day", age_start: 1, age_end: 3, value: 1.2, gender: "Both" },
    { nutrient: "Manganese", source: "FNB", type: "AI", unit: "mg/day", age_start: 4, age_end: 8, value: 1.5, gender: "Both" },
    { nutrient: "Manganese", source: "FNB", type: "AI", unit: "mg/day", age_start: 9, age_end: 13, value: 1.9, gender: "Male" },
    { nutrient: "Manganese", source: "FNB", type: "AI", unit: "mg/day", age_start: 9, age_end: 13, value: 1.6, gender: "Female" },
    { nutrient: "Manganese", source: "FNB", type: "AI", unit: "mg/day", age_start: 14, age_end: 18, value: 2.2, gender: "Male" },
    { nutrient: "Manganese", source: "FNB", type: "AI", unit: "mg/day", age_start: 14, age_end: 18, value: 1.6, gender: "Female" },
    { nutrient: "Manganese", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 2, gender: "Both" },
    { nutrient: "Manganese", source: "FNB", type: "UL", unit: "mg/day", age_start: 4, age_end: 8, value: 3, gender: "Both" },
    { nutrient: "Manganese", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 13, value: 6, gender: "Both" },
    { nutrient: "Manganese", source: "FNB", type: "UL", unit: "mg/day", age_start: 14, age_end: 18, value: 9, gender: "Both" },
    { nutrient: "Manganese", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 2, gender: "Both" },
    // Molybdenum (μg/day)
    { nutrient: "Molybdenum", source: "EFSA", type: "Safe and adequate intake", unit: "μg/day", age_start: 1, age_end: 3, value: 20, gender: "Both" },
    { nutrient: "Molybdenum", source: "EFSA", type: "Safe and adequate intake", unit: "μg/day", age_start: 4, age_end: 6, value: 30, gender: "Both" },
    { nutrient: "Molybdenum", source: "EFSA", type: "Safe and adequate intake", unit: "μg/day", age_start: 7, age_end: 10, value: 45, gender: "Both" },
    { nutrient: "Molybdenum", source: "EFSA", type: "Safe and adequate intake", unit: "μg/day", age_start: 11, age_end: 17, value: 65, gender: "Both" },
    { nutrient: "Molybdenum", source: "FNB", type: "RDA", unit: "μg/day", age_start: 1, age_end: 3, value: 17, gender: "Both" },
    { nutrient: "Molybdenum", source: "FNB", type: "RDA", unit: "μg/day", age_start: 4, age_end: 8, value: 22, gender: "Both" },
    { nutrient: "Molybdenum", source: "FNB", type: "RDA", unit: "μg/day", age_start: 9, age_end: 13, value: 34, gender: "Both" },
    { nutrient: "Molybdenum", source: "FNB", type: "RDA", unit: "μg/day", age_start: 14, age_end: 18, value: 43, gender: "Both" },
    { nutrient: "Molybdenum", source: "FNB", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 300, gender: "Both" },
    { nutrient: "Molybdenum", source: "FNB", type: "UL", unit: "μg/day", age_start: 4, age_end: 8, value: 600, gender: "Both" },
    { nutrient: "Molybdenum", source: "FNB", type: "UL", unit: "μg/day", age_start: 9, age_end: 13, value: 1100, gender: "Both" },
    { nutrient: "Molybdenum", source: "FNB", type: "UL", unit: "μg/day", age_start: 14, age_end: 18, value: 1700, gender: "Both" },
    { nutrient: "Molybdenum", source: "TFC", type: "DRV", unit: "μg/day", age_start: 4, age_end: 18, value: 50, gender: "Both" },
    // Niacin (mg/day)
    { nutrient: "Niacin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 1, age_end: 3, value: 5, gender: "Both" },
    { nutrient: "Niacin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 4, age_end: 6, value: 8, gender: "Both" },
    { nutrient: "Niacin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 7, age_end: 10, value: 11, gender: "Both" },
    { nutrient: "Niacin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 14, value: 15, gender: "Male" },
    { nutrient: "Niacin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 14, value: 13, gender: "Female" },
    { nutrient: "Niacin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 16, gender: "Male" },
    { nutrient: "Niacin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 13, gender: "Female" },
    { nutrient: "Niacin", source: "EFSA", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 150, gender: "Both" },
    { nutrient: "Niacin", source: "EFSA", type: "UL", unit: "mg/day", age_start: 4, age_end: 6, value: 200, gender: "Both" },
    { nutrient: "Niacin", source: "EFSA", type: "UL", unit: "mg/day", age_start: 7, age_end: 10, value: 300, gender: "Both" },
    { nutrient: "Niacin", source: "EFSA", type: "UL", unit: "mg/day", age_start: 11, age_end: 14, value: 500, gender: "Both" },
    { nutrient: "Niacin", source: "EFSA", type: "UL", unit: "mg/day", age_start: 15, age_end: 17, value: 600, gender: "Both" },
    { nutrient: "Niacin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 6, gender: "Both" },
    { nutrient: "Niacin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 8, gender: "Both" },
    { nutrient: "Niacin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 13, value: 12, gender: "Both" },
    { nutrient: "Niacin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 16, gender: "Male" },
    { nutrient: "Niacin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 14, gender: "Female" },
    { nutrient: "Niacin", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 10, gender: "Both" },
    { nutrient: "Niacin", source: "FNB", type: "UL", unit: "mg/day", age_start: 4, age_end: 8, value: 15, gender: "Both" },
    { nutrient: "Niacin", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 13, value: 20, gender: "Both" },
    { nutrient: "Niacin", source: "FNB", type: "UL", unit: "mg/day", age_start: 14, age_end: 18, value: 30, gender: "Both" },
    { nutrient: "Niacin", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 16, gender: "Both" },
    { nutrient: "Niacin", source: "TFC", type: "DML", unit: "mg/day", age_start: 4, age_end: 10, value: 450, gender: "Both" },
    { nutrient: "Niacin", source: "TFC", type: "DML", unit: "mg/day", age_start: 11, age_end: 18, value: 900, gender: "Both" },
    // Pantothenic Acid (mg/day)
    { nutrient: "Pantothenic Acid", source: "EFSA", type: "AI", unit: "mg/day", age_start: 1, age_end: 3, value: 3, gender: "Both" },
    { nutrient: "Pantothenic Acid", source: "EFSA", type: "AI", unit: "mg/day", age_start: 4, age_end: 10, value: 4, gender: "Both" },
    { nutrient: "Pantothenic Acid", source: "EFSA", type: "AI", unit: "mg/day", age_start: 11, age_end: 17, value: 5, gender: "Both" },
    { nutrient: "Pantothenic Acid", source: "FNB", type: "AI", unit: "mg/day", age_start: 1, age_end: 3, value: 2, gender: "Both" },
    { nutrient: "Pantothenic Acid", source: "FNB", type: "AI", unit: "mg/day", age_start: 4, age_end: 8, value: 3, gender: "Both" },
    { nutrient: "Pantothenic Acid", source: "FNB", type: "AI", unit: "mg/day", age_start: 9, age_end: 13, value: 4, gender: "Both" },
    { nutrient: "Pantothenic Acid", source: "FNB", type: "AI", unit: "mg/day", age_start: 14, age_end: 18, value: 5, gender: "Both" },
    { nutrient: "Pantothenic Acid", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 6, gender: "Both" },
    // Phosphorus (mg/day)
    { nutrient: "Phosphorus", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 1, age_end: 3, value: 250, gender: "Both" },
    { nutrient: "Phosphorus", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 4, age_end: 10, value: 550, gender: "Both" },
    { nutrient: "Phosphorus", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 17, value: 700, gender: "Both" },
    { nutrient: "Phosphorus", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 460, gender: "Both" },
    { nutrient: "Phosphorus", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 500, gender: "Both" },
    { nutrient: "Phosphorus", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 18, value: 1250, gender: "Both" },
    { nutrient: "Phosphorus", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 700, gender: "Both" },
    // Potassium (g/day)
    { nutrient: "Potassium", source: "EFSA", type: "AI", unit: "g/day", age_start: 1, age_end: 3, value: 1.1, gender: "Both" },
    { nutrient: "Potassium", source: "EFSA", type: "AI", unit: "g/day", age_start: 4, age_end: 6, value: 2.0, gender: "Both" },
    { nutrient: "Potassium", source: "EFSA", type: "AI", unit: "g/day", age_start: 7, age_end: 9, value: 2.9, gender: "Both" },
    { nutrient: "Potassium", source: "EFSA", type: "AI", unit: "g/day", age_start: 10, age_end: 14, value: 3.7, gender: "Both" },
    { nutrient: "Potassium", source: "EFSA", type: "AI", unit: "g/day", age_start: 15, age_end: 17, value: 4.0, gender: "Both" },
    { nutrient: "Potassium", source: "FNB", type: "AI", unit: "g/day", age_start: 1, age_end: 3, value: 3.0, gender: "Both" },
    { nutrient: "Potassium", source: "FNB", type: "AI", unit: "g/day", age_start: 4, age_end: 8, value: 3.8, gender: "Both" },
    { nutrient: "Potassium", source: "FNB", type: "AI", unit: "g/day", age_start: 9, age_end: 13, value: 4.5, gender: "Both" },
    { nutrient: "Potassium", source: "FNB", type: "AI", unit: "g/day", age_start: 14, age_end: 18, value: 4.7, gender: "Both" },
    { nutrient: "Potassium", source: "TFC", type: "DRV", unit: "g/day", age_start: 4, age_end: 18, value: 2, gender: "Both" },
    // Riboflavin (mg/day)
    { nutrient: "Riboflavin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 1, age_end: 3, value: 0.6, gender: "Both" },
    { nutrient: "Riboflavin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 4, age_end: 6, value: 0.8, gender: "Both" },
    { nutrient: "Riboflavin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 7, age_end: 10, value: 1.1, gender: "Both" },
    { nutrient: "Riboflavin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 14, value: 1.4, gender: "Both" },
    { nutrient: "Riboflavin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 1.6, gender: "Both" },
    { nutrient: "Riboflavin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 0.5, gender: "Both" },
    { nutrient: "Riboflavin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 0.6, gender: "Both" },
    { nutrient: "Riboflavin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 13, value: 0.9, gender: "Both" },
    { nutrient: "Riboflavin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 1.3, gender: "Male" },
    { nutrient: "Riboflavin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 1.0, gender: "Female" },
    { nutrient: "Riboflavin", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 1.4, gender: "Both" },
    // Selenium (μg/day)
    { nutrient: "Selenium", source: "EFSA", type: "AI", unit: "μg/day", age_start: 1, age_end: 3, value: 20, gender: "Both" },
    { nutrient: "Selenium", source: "EFSA", type: "AI", unit: "μg/day", age_start: 4, age_end: 6, value: 30, gender: "Both" },
    { nutrient: "Selenium", source: "EFSA", type: "AI", unit: "μg/day", age_start: 7, age_end: 10, value: 45, gender: "Both" },
    { nutrient: "Selenium", source: "EFSA", type: "AI", unit: "μg/day", age_start: 11, age_end: 14, value: 55, gender: "Both" },
    { nutrient: "Selenium", source: "EFSA", type: "AI", unit: "μg/day", age_start: 15, age_end: 17, value: 70, gender: "Both" },
    { nutrient: "Selenium", source: "EFSA", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 60, gender: "Both" },
    { nutrient: "Selenium", source: "EFSA", type: "UL", unit: "μg/day", age_start: 4, age_end: 6, value: 85, gender: "Both" },
    { nutrient: "Selenium", source: "EFSA", type: "UL", unit: "μg/day", age_start: 7, age_end: 10, value: 130, gender: "Both" },
    { nutrient: "Selenium", source: "EFSA", type: "UL", unit: "μg/day", age_start: 11, age_end: 14, value: 200, gender: "Both" },
    { nutrient: "Selenium", source: "EFSA", type: "UL", unit: "μg/day", age_start: 15, age_end: 17, value: 250, gender: "Both" },
    { nutrient: "Selenium", source: "FNB", type: "RDA", unit: "μg/day", age_start: 1, age_end: 3, value: 20, gender: "Both" },
    { nutrient: "Selenium", source: "FNB", type: "RDA", unit: "μg/day", age_start: 4, age_end: 8, value: 30, gender: "Both" },
    { nutrient: "Selenium", source: "FNB", type: "RDA", unit: "μg/day", age_start: 9, age_end: 13, value: 40, gender: "Both" },
    { nutrient: "Selenium", source: "FNB", type: "RDA", unit: "μg/day", age_start: 14, age_end: 18, value: 55, gender: "Both" },
    { nutrient: "Selenium", source: "FNB", type: "UL", unit: "μg/day", age_start: 1, age_end: 3, value: 90, gender: "Both" },
    { nutrient: "Selenium", source: "FNB", type: "UL", unit: "μg/day", age_start: 4, age_end: 8, value: 150, gender: "Both" },
    { nutrient: "Selenium", source: "FNB", type: "UL", unit: "μg/day", age_start: 9, age_end: 13, value: 280, gender: "Both" },
    { nutrient: "Selenium", source: "FNB", type: "UL", unit: "μg/day", age_start: 14, age_end: 18, value: 400, gender: "Both" },
    { nutrient: "Selenium", source: "TFC", type: "DRV", unit: "μg/day", age_start: 4, age_end: 18, value: 55, gender: "Both" },
    // Sodium (g/day)
    { nutrient: "Sodium", source: "EFSA", type: "Safe and adequate intake", unit: "g/day", age_start: 1, age_end: 3, value: 1.1, gender: "Both" },
    { nutrient: "Sodium", source: "EFSA", type: "Safe and adequate intake", unit: "g/day", age_start: 4, age_end: 6, value: 1.2, gender: "Both" },
    { nutrient: "Sodium", source: "EFSA", type: "Safe and adequate intake", unit: "g/day", age_start: 7, age_end: 10, value: 1.3, gender: "Both" },
    { nutrient: "Sodium", source: "EFSA", type: "Safe and adequate intake", unit: "g/day", age_start: 11, age_end: 17, value: 1.5, gender: "Both" },
    { nutrient: "Sodium", source: "FNB", type: "AI", unit: "g/day", age_start: 1, age_end: 3, value: 1.0, gender: "Both" },
    { nutrient: "Sodium", source: "FNB", type: "AI", unit: "g/day", age_start: 4, age_end: 8, value: 1.2, gender: "Both" },
    { nutrient: "Sodium", source: "FNB", type: "AI", unit: "g/day", age_start: 9, age_end: 18, value: 1.5, gender: "Both" },
    { nutrient: "Sodium", source: "TFC", type: "DRV", unit: "g/day", age_start: 4, age_end: 18, value: 2.4, gender: "Both" },
    // Thiamin (mg/day)
    { nutrient: "Thiamin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 1, age_end: 3, value: 0.4, gender: "Both" },
    { nutrient: "Thiamin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 4, age_end: 6, value: 0.6, gender: "Both" },
    { nutrient: "Thiamin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 7, age_end: 9, value: 0.8, gender: "Both" },
    { nutrient: "Thiamin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 10, age_end: 14, value: 1.0, gender: "Male" },
    { nutrient: "Thiamin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 10, age_end: 14, value: 0.9, gender: "Female" },
    { nutrient: "Thiamin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 1.2, gender: "Male" },
    { nutrient: "Thiamin", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 1.1, gender: "Female" },
    { nutrient: "Thiamin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 0.5, gender: "Both" },
    { nutrient: "Thiamin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 0.6, gender: "Both" },
    { nutrient: "Thiamin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 13, value: 0.9, gender: "Both" },
    { nutrient: "Thiamin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 1.2, gender: "Male" },
    { nutrient: "Thiamin", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 1.0, gender: "Female" },
    { nutrient: "Thiamin", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 1.1, gender: "Both" },
    // Vitamin B12 (μg/day)
    { nutrient: "Vitamin B12", source: "EFSA", type: "AI", unit: "μg/day", age_start: 1, age_end: 3, value: 1.5, gender: "Both" },
    { nutrient: "Vitamin B12", source: "EFSA", type: "AI", unit: "μg/day", age_start: 4, age_end: 6, value: 2.5, gender: "Both" },
    { nutrient: "Vitamin B12", source: "EFSA", type: "AI", unit: "μg/day", age_start: 7, age_end: 10, value: 2.5, gender: "Both" },
    { nutrient: "Vitamin B12", source: "EFSA", type: "AI", unit: "μg/day", age_start: 11, age_end: 14, value: 3.5, gender: "Both" },
    { nutrient: "Vitamin B12", source: "EFSA", type: "AI", unit: "μg/day", age_start: 15, age_end: 17, value: 4.0, gender: "Both" },
    { nutrient: "Vitamin B12", source: "FNB", type: "RDA", unit: "μg/day", age_start: 1, age_end: 3, value: 0.9, gender: "Both" },
    { nutrient: "Vitamin B12", source: "FNB", type: "RDA", unit: "μg/day", age_start: 4, age_end: 8, value: 1.2, gender: "Both" },
    { nutrient: "Vitamin B12", source: "FNB", type: "RDA", unit: "μg/day", age_start: 9, age_end: 13, value: 1.8, gender: "Both" },
    { nutrient: "Vitamin B12", source: "FNB", type: "RDA", unit: "μg/day", age_start: 14, age_end: 18, value: 2.4, gender: "Both" },
    { nutrient: "Vitamin B12", source: "TFC", type: "DRV", unit: "μg/day", age_start: 4, age_end: 18, value: 2.5, gender: "Both" },
    // Vitamin B6 (mg/day)
    { nutrient: "Vitamin B6", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 1, age_end: 3, value: 0.6, gender: "Both" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 4, age_end: 6, value: 0.9, gender: "Both" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 7, age_end: 10, value: 1.1, gender: "Both" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 14, value: 1.4, gender: "Male" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 14, value: 1.3, gender: "Female" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 1.7, gender: "Male" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 1.4, gender: "Female" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 7, gender: "Both" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "UL", unit: "mg/day", age_start: 4, age_end: 6, value: 10, gender: "Both" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "UL", unit: "mg/day", age_start: 7, age_end: 10, value: 15, gender: "Both" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "UL", unit: "mg/day", age_start: 11, age_end: 14, value: 20, gender: "Both" },
    { nutrient: "Vitamin B6", source: "EFSA", type: "UL", unit: "mg/day", age_start: 15, age_end: 17, value: 25, gender: "Both" },
    { nutrient: "Vitamin B6", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 0.5, gender: "Both" },
    { nutrient: "Vitamin B6", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 0.6, gender: "Both" },
    { nutrient: "Vitamin B6", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 13, value: 1.0, gender: "Both" },
    { nutrient: "Vitamin B6", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 1.3, gender: "Male" },
    { nutrient: "Vitamin B6", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 1.2, gender: "Female" },
    { nutrient: "Vitamin B6", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 30, gender: "Both" },
    { nutrient: "Vitamin B6", source: "FNB", type: "UL", unit: "mg/day", age_start: 4, age_end: 8, value: 40, gender: "Both" },
    { nutrient: "Vitamin B6", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 13, value: 60, gender: "Both" },
    { nutrient: "Vitamin B6", source: "FNB", type: "UL", unit: "mg/day", age_start: 14, age_end: 18, value: 80, gender: "Both" },
    { nutrient: "Vitamin B6", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 1.4, gender: "Both" },
    // Vitamin C (mg/day)
    { nutrient: "Vitamin C", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 1, age_end: 3, value: 20, gender: "Both" },
    { nutrient: "Vitamin C", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 4, age_end: 6, value: 30, gender: "Both" },
    { nutrient: "Vitamin C", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 7, age_end: 10, value: 50, gender: "Both" },
    { nutrient: "Vitamin C", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 14, value: 80, gender: "Both" },
    { nutrient: "Vitamin C", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 110, gender: "Male" },
    { nutrient: "Vitamin C", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 95, gender: "Female" },
    { nutrient: "Vitamin C", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 15, gender: "Both" },
    { nutrient: "Vitamin C", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 25, gender: "Both" },
    { nutrient: "Vitamin C", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 13, value: 45, gender: "Both" },
    { nutrient: "Vitamin C", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 75, gender: "Male" },
    { nutrient: "Vitamin C", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 65, gender: "Female" },
    { nutrient: "Vitamin C", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 400, gender: "Both" },
    { nutrient: "Vitamin C", source: "FNB", type: "UL", unit: "mg/day", age_start: 4, age_end: 8, value: 650, gender: "Both" },
    { nutrient: "Vitamin C", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 13, value: 1200, gender: "Both" },
    { nutrient: "Vitamin C", source: "FNB", type: "UL", unit: "mg/day", age_start: 14, age_end: 18, value: 1800, gender: "Both" },
    { nutrient: "Vitamin C", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 80, gender: "Both" },
    // Vitamin D (μg/day)
    { nutrient: "Vitamin D", source: "EFSA", type: "AI", unit: "μg/day", age_start: 1, age_end: 17, value: 15, gender: "Both" },
    { nutrient: "Vitamin D", source: "EFSA", type: "UL", unit: "μg/day", age_start: 1, age_end: 10, value: 50, gender: "Both" },
    { nutrient: "Vitamin D", source: "EFSA", type: "UL", unit: "μg/day", age_start: 11, age_end: 17, value: 100, gender: "Both" },
    { nutrient: "Vitamin D", source: "FNB", type: "AI", unit: "μg/day", age_start: 1, age_end: 18, value: 5, gender: "Both" },
    { nutrient: "Vitamin D", source: "FNB", type: "UL", unit: "μg/day", age_start: 1, age_end: 18, value: 50, gender: "Both" },
    { nutrient: "Vitamin D", source: "TFC", type: "DRV", unit: "μg/day", age_start: 4, age_end: 18, value: 5, gender: "Both" },
    { nutrient: "Vitamin D", source: "TFC", type: "DML", unit: "μg/day", age_start: 4, age_end: 18, value: 25, gender: "Both" },
    // Vitamin E (mg/day)
    { nutrient: "Vitamin E", source: "EFSA", type: "AI", unit: "mg/day", age_start: 1, age_end: 2, value: 6, gender: "Both" },
    { nutrient: "Vitamin E", source: "EFSA", type: "AI", unit: "mg/day", age_start: 3, age_end: 3, value: 9, gender: "Both" },
    { nutrient: "Vitamin E", source: "EFSA", type: "AI", unit: "mg/day", age_start: 4, age_end: 9, value: 9, gender: "Both" },
    { nutrient: "Vitamin E", source: "EFSA", type: "AI", unit: "mg/day", age_start: 10, age_end: 10, value: 13, gender: "Male" },
    { nutrient: "Vitamin E", source: "EFSA", type: "AI", unit: "mg/day", age_start: 10, age_end: 10, value: 11, gender: "Female" },
    { nutrient: "Vitamin E", source: "EFSA", type: "AI", unit: "mg/day", age_start: 11, age_end: 14, value: 13, gender: "Male" },
    { nutrient: "Vitamin E", source: "EFSA", type: "AI", unit: "mg/day", age_start: 11, age_end: 14, value: 11, gender: "Female" },
    { nutrient: "Vitamin E", source: "EFSA", type: "AI", unit: "mg/day", age_start: 15, age_end: 17, value: 13, gender: "Male" },
    { nutrient: "Vitamin E", source: "EFSA", type: "AI", unit: "mg/day", age_start: 15, age_end: 17, value: 12, gender: "Female" },
    { nutrient: "Vitamin E", source: "EFSA", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 100, gender: "Both" },
    { nutrient: "Vitamin E", source: "EFSA", type: "UL", unit: "mg/day", age_start: 4, age_end: 6, value: 120, gender: "Both" },
    { nutrient: "Vitamin E", source: "EFSA", type: "UL", unit: "mg/day", age_start: 7, age_end: 10, value: 160, gender: "Both" },
    { nutrient: "Vitamin E", source: "EFSA", type: "UL", unit: "mg/day", age_start: 11, age_end: 14, value: 220, gender: "Both" },
    { nutrient: "Vitamin E", source: "EFSA", type: "UL", unit: "mg/day", age_start: 15, age_end: 17, value: 260, gender: "Both" },
    { nutrient: "Vitamin E", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 6, gender: "Both" },
    { nutrient: "Vitamin E", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 7, gender: "Both" },
    { nutrient: "Vitamin E", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 13, value: 11, gender: "Both" },
    { nutrient: "Vitamin E", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 15, gender: "Both" },
    { nutrient: "Vitamin E", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 200, gender: "Both" },
    { nutrient: "Vitamin E", source: "FNB", type: "UL", unit: "mg/day", age_start: 4, age_end: 8, value: 300, gender: "Both" },
    { nutrient: "Vitamin E", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 13, value: 600, gender: "Both" },
    { nutrient: "Vitamin E", source: "FNB", type: "UL", unit: "mg/day", age_start: 14, age_end: 18, value: 800, gender: "Both" },
    { nutrient: "Vitamin E", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 12, gender: "Both" },
    { nutrient: "Vitamin E", source: "TFC", type: "DML", unit: "mg/day", age_start: 4, age_end: 18, value: 270, gender: "Both" },
    // Zinc (mg/day)
    { nutrient: "Zinc", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 1, age_end: 3, value: 5.5, gender: "Both" },
    { nutrient: "Zinc", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 4, age_end: 6, value: 6.9, gender: "Both" },
    { nutrient: "Zinc", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 7, age_end: 10, value: 9.4, gender: "Both" },
    { nutrient: "Zinc", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 14, value: 12.7, gender: "Male" },
    { nutrient: "Zinc", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 11, age_end: 14, value: 10.2, gender: "Female" },
    { nutrient: "Zinc", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 12.9, gender: "Male" },
    { nutrient: "Zinc", source: "EFSA", type: "PRI", unit: "mg/day", age_start: 15, age_end: 17, value: 9.3, gender: "Female" },
    { nutrient: "Zinc", source: "EFSA", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 10, gender: "Both" },
    { nutrient: "Zinc", source: "EFSA", type: "UL", unit: "mg/day", age_start: 4, age_end: 6, value: 12, gender: "Both" },
    { nutrient: "Zinc", source: "EFSA", type: "UL", unit: "mg/day", age_start: 7, age_end: 10, value: 16, gender: "Both" },
    { nutrient: "Zinc", source: "EFSA", type: "UL", unit: "mg/day", age_start: 11, age_end: 14, value: 22, gender: "Both" },
    { nutrient: "Zinc", source: "EFSA", type: "UL", unit: "mg/day", age_start: 15, age_end: 17, value: 26, gender: "Both" },
    { nutrient: "Zinc", source: "FNB", type: "RDA", unit: "mg/day", age_start: 1, age_end: 3, value: 3, gender: "Both" },
    { nutrient: "Zinc", source: "FNB", type: "RDA", unit: "mg/day", age_start: 4, age_end: 8, value: 5, gender: "Both" },
    { nutrient: "Zinc", source: "FNB", type: "RDA", unit: "mg/day", age_start: 9, age_end: 13, value: 8, gender: "Both" },
    { nutrient: "Zinc", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 11, gender: "Male" },
    { nutrient: "Zinc", source: "FNB", type: "RDA", unit: "mg/day", age_start: 14, age_end: 18, value: 9, gender: "Female" },
    { nutrient: "Zinc", source: "FNB", type: "UL", unit: "mg/day", age_start: 1, age_end: 3, value: 7, gender: "Both" },
    { nutrient: "Zinc", source: "FNB", type: "UL", unit: "mg/day", age_start: 4, age_end: 8, value: 12, gender: "Both" },
    { nutrient: "Zinc", source: "FNB", type: "UL", unit: "mg/day", age_start: 9, age_end: 13, value: 23, gender: "Both" },
    { nutrient: "Zinc", source: "FNB", type: "UL", unit: "mg/day", age_start: 14, age_end: 18, value: 34, gender: "Both" },
    { nutrient: "Zinc", source: "TFC", type: "DRV", unit: "mg/day", age_start: 4, age_end: 18, value: 10, gender: "Both" },
    { nutrient: "Zinc", source: "TFC", type: "DML", unit: "mg/day", age_start: 4, age_end: 18, value: 15, gender: "Both" },
];
